NIMSFORESTFOLDERS_PATH ?= ../nimsforestfolders

-include $(NIMSFORESTFOLDERS_PATH)/MAKEFILE.nimsforestfolders

.PHONY: test
test:
	rm -rf tmp && \
	mkdir -p tmp/tools/nimsforestorganize && \
	cd tmp/tools/nimsforestorganize && \
	cp $(CURDIR)/MAKEFILE.nimsforestorganize . && \
	cp -r $(CURDIR)/docs . && \
	echo "-include $(NIMSFORESTFOLDERS_PATH)/MAKEFILE.nimsforestfolders" > ../../Makefile && \
	make -f MAKEFILE.nimsforestorganize nimsforestorganize-addtomainmake NIMSFORESTFOLDERS_PATH=$(NIMSFORESTFOLDERS_PATH) && \
	cd ../.. && \
	make nimsforestorganize-hello NIMSFORESTFOLDERS_PATH=$(NIMSFORESTFOLDERS_PATH) && \
	DOCS_PATH=docs make nimsforestorganize-init NIMSFORESTFOLDERS_PATH=$(NIMSFORESTFOLDERS_PATH) && \
	DOCS_PATH=docs make nimsforestorganize-lint NIMSFORESTFOLDERS_PATH=$(NIMSFORESTFOLDERS_PATH) && \
	cd ..